fix(odm): use allowDiskUse
Saebasol/Heliotrope pull request #277
Opened 2022-08-23 03:52 UTC by ombe1229

close #276 

### Check Box

- [ ] Changes to this PR can be deployed immediately.

2022-08-23 04:07 UTC, SaidBySolo requested changes

2022-08-23 04:07 UTC, SaidBySolo commented on heliotrope/database/odm/__init__.py
> +            ).next()
Check again

2022-09-01 21:10 UTC, FluffyDiscord commented
How is it going?

2022-09-03 09:51 UTC, SaidBySolo commented
@ombe1229 

As we discussed last time, we don't want to merge the typo-related commits yet.

Please force push after manipulating the commit record

2022-09-04 07:39 UTC, merged